---
- name: TLT media lab machine setup
  hosts: localhost
  become: yes

  tasks:
    - name: "change host name"
      command: scutil --set HostName {{inventory_hostname}}
      become: true
      become_user: root
    
    - name: "change computer name"
      command: scutil --set ComputerName {{inventory_hostname}}
      become: true
      become_user: root

    - name: "change brew group settings"
      shell: chgrp -R admin /usr/local/*
      become: true
      become_user: root

    - name: "change brew file permissions"
      shell: chmod -R g+w /usr/local/*
      become: true
      become_user: root

    - name: "change brew group settings"
      shell: chgrp -R admin /opt
      become: true
      become_user: root
  
    - name: "change brew file permissions"
      shell: chmod -R g+w /opt
      become: true
      become_user: root
  
    - name: Copy brew install script
      ansible.builtin.copy:
        src: scripts/install_brew.sh
        dest: /Users/Shared/install_brew.sh
        mode: '0777'

    - name: Copy makemeadmin script
      ansible.builtin.copy:
        src: /Users/xiqchen/ansible/scripts/makemeadmin.command
        dest: /Users/Shared/makemeadmin.command
        mode: '0777'
    
    - name: Copy host file
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts

    - name: Copy sudoer file for permissions
      become: true
      become_user: root
      ansible.builtin.copy:
        src: scripts/sudoers
        dest: /etc/sudoers

    - name: "install brew"
      shell: NONINTERACTIVE=1 /bin/bash /User/Shared/install_brew.sh 
      become: false

