---
- name: TLT media lab machine setup
  hosts: localhost
  become: yes

  tasks:
    - name: "change host name"
      command: scutil --set HostName {{inventory_hostname}}
      become: true
      become_user: root
    
    - name: "change computer name"
      command: scutil --set ComputerName {{inventory_hostname}}
      become: true
      become_user: root

    - name: "change brew group settings"
      shell: chgrp -R admin /usr/local/*
      become: true
      become_user: root

    - name: "change brew file permissions"
      shell: chmod -R g+w /usr/local/*
      become: true
      become_user: root

    - name: "change brew group settings"
      shell: chgrp -R admin /opt
      become: true
      become_user: root
  
    - name: "change brew file permissions"
      shell: chmod -R g+w /opt
      become: true
      become_user: root

    - name: "change brew ca permissions"
      shell: chown -R ${USER}:admin /usr/local/Cellar/
      become: true
      become_user: root
  
    - name: Copy brew install script
      ansible.builtin.copy:
        src: scripts/commands/install_brew.sh
        dest: /Users/Shared/install_brew.sh
        mode: '0777'

    - name: Copy makemeadmin script
      ansible.builtin.copy:
        src: /Users/xiqchen/ansible/scripts/makemeadmin.command
        dest: /Users/Shared/makemeadmin.command
        mode: '0777'
    
    - name: Copy host file
      ansible.builtin.copy:
        src: scripts/hosts
        dest: /etc/hosts

    - name: Copy sudoer file for permissions
      become: true
      become_user: root
      ansible.builtin.copy:
        src: scripts/sudoers
        dest: /etc/sudoers

    - name: Install Homebrew
      shell: |
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew/bin/brew', '/usr/local/bin/brew') }}"
      become: false
  
    - name: Add Homebrew to PATH for current user
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'eval "$({{ (ansible_machine == "arm64") | ternary("/opt/homebrew", "/usr/local") }}/bin/brew shellenv)"'
        create: true
        state: present
      become: false

    - name: Verify brew installation
      command: "{{ brew_prefix }}/bin/brew --version"
      register: brew_version
      changed_when: false
    - debug:
        msg: "Installed Homebrew version: {{ brew_version.stdout }}"
