---
# roles/ollama_gateway/tasks/ensure_services.yml
- name: Set OLLAMA_HOST environment variable in .zshrc (or .bashrc)
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc" # Adjust path based on user and shell
    line: 'export OLLAMA_HOST="127.0.0.1:{{ local_ollama_port }}"'
    create: true
  become: yes

- name: Check if Ollama application is running
  ansible.builtin.command: pgrep -f "/Applications/Ollama.app"
  register: ollama_process
  changed_when: false
  failed_when: false

- name: Ensure local Ollama application is running
  ansible.builtin.command: open -a Ollama
  when: ollama_process.rc != 0

- name: Ensure Nginx is present
  community.general.homebrew:
    name: nginx
    state: present
  become: false